#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("EsMo.Android.WeiBo.Resource", IsApplication=true)]

namespace EsMo.Android.WeiBo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::EsMo.Android.Support.Resource.Attribute.layoutManager = global::EsMo.Android.WeiBo.Resource.Attribute.layoutManager;
			global::EsMo.Android.Support.Resource.Attribute.reverseLayout = global::EsMo.Android.WeiBo.Resource.Attribute.reverseLayout;
			global::EsMo.Android.Support.Resource.Attribute.spanCount = global::EsMo.Android.WeiBo.Resource.Attribute.spanCount;
			global::EsMo.Android.Support.Resource.Attribute.stackFromEnd = global::EsMo.Android.WeiBo.Resource.Attribute.stackFromEnd;
			global::EsMo.Android.Support.Resource.Dimension.item_touch_helper_max_drag_scroll_per_frame = global::EsMo.Android.WeiBo.Resource.Dimension.item_touch_helper_max_drag_scroll_per_frame;
			global::EsMo.Android.Support.Resource.Dimension.item_touch_helper_swipe_escape_max_velocity = global::EsMo.Android.WeiBo.Resource.Dimension.item_touch_helper_swipe_escape_max_velocity;
			global::EsMo.Android.Support.Resource.Dimension.item_touch_helper_swipe_escape_velocity = global::EsMo.Android.WeiBo.Resource.Dimension.item_touch_helper_swipe_escape_velocity;
			global::EsMo.Android.Support.Resource.Id.item_touch_helper_previous_elevation = global::EsMo.Android.WeiBo.Resource.Id.item_touch_helper_previous_elevation;
			global::EsMo.Android.Support.Resource.String.ApplicationName = global::EsMo.Android.WeiBo.Resource.String.ApplicationName;
			global::EsMo.Android.Support.Resource.String.Hello = global::EsMo.Android.WeiBo.Resource.String.Hello;
			global::EsMo.Android.Support.Resource.Styleable.RecyclerView = global::EsMo.Android.WeiBo.Resource.Styleable.RecyclerView;
			global::EsMo.Android.Support.Resource.Styleable.RecyclerView_android_orientation = global::EsMo.Android.WeiBo.Resource.Styleable.RecyclerView_android_orientation;
			global::EsMo.Android.Support.Resource.Styleable.RecyclerView_layoutManager = global::EsMo.Android.WeiBo.Resource.Styleable.RecyclerView_layoutManager;
			global::EsMo.Android.Support.Resource.Styleable.RecyclerView_reverseLayout = global::EsMo.Android.WeiBo.Resource.Styleable.RecyclerView_reverseLayout;
			global::EsMo.Android.Support.Resource.Styleable.RecyclerView_spanCount = global::EsMo.Android.WeiBo.Resource.Styleable.RecyclerView_spanCount;
			global::EsMo.Android.Support.Resource.Styleable.RecyclerView_stackFromEnd = global::EsMo.Android.WeiBo.Resource.Styleable.RecyclerView_stackFromEnd;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxBind = global::EsMo.Android.WeiBo.Resource.Attribute.MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::EsMo.Android.WeiBo.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxGroupItemTemplate = global::EsMo.Android.WeiBo.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxItemTemplate = global::EsMo.Android.WeiBo.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxLang = global::EsMo.Android.WeiBo.Resource.Attribute.MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxSource = global::EsMo.Android.WeiBo.Resource.Attribute.MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxTemplate = global::EsMo.Android.WeiBo.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Id.MvvmCrossTagId = global::EsMo.Android.WeiBo.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Binding.Droid.Resource.Id.MvxBindingTagUnique = global::EsMo.Android.WeiBo.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding = global::EsMo.Android.WeiBo.Resource.Styleable.MvxBinding;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxBind = global::EsMo.Android.WeiBo.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxLang = global::EsMo.Android.WeiBo.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl = global::EsMo.Android.WeiBo.Resource.Styleable.MvxControl;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::EsMo.Android.WeiBo.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView = global::EsMo.Android.WeiBo.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::EsMo.Android.WeiBo.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView = global::EsMo.Android.WeiBo.Resource.Styleable.MvxImageView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView_MvxSource = global::EsMo.Android.WeiBo.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView = global::EsMo.Android.WeiBo.Resource.Styleable.MvxListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::EsMo.Android.WeiBo.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::EsMo.Android.WeiBo.Resource.Styleable.MvxListView_MvxItemTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.MvxBind = global::EsMo.Android.WeiBo.Resource.Attribute.MvxBind;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.MvxDropDownItemTemplate = global::EsMo.Android.WeiBo.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.MvxGroupItemTemplate = global::EsMo.Android.WeiBo.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.MvxItemTemplate = global::EsMo.Android.WeiBo.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.MvxLang = global::EsMo.Android.WeiBo.Resource.Attribute.MvxLang;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.MvxSource = global::EsMo.Android.WeiBo.Resource.Attribute.MvxSource;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.MvxTemplate = global::EsMo.Android.WeiBo.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.MvxTemplateSelector = global::EsMo.Android.WeiBo.Resource.Attribute.MvxTemplateSelector;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.layoutManager = global::EsMo.Android.WeiBo.Resource.Attribute.layoutManager;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.reverseLayout = global::EsMo.Android.WeiBo.Resource.Attribute.reverseLayout;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.spanCount = global::EsMo.Android.WeiBo.Resource.Attribute.spanCount;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.stackFromEnd = global::EsMo.Android.WeiBo.Resource.Attribute.stackFromEnd;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.item_touch_helper_max_drag_scroll_per_frame = global::EsMo.Android.WeiBo.Resource.Dimension.item_touch_helper_max_drag_scroll_per_frame;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.item_touch_helper_swipe_escape_max_velocity = global::EsMo.Android.WeiBo.Resource.Dimension.item_touch_helper_swipe_escape_max_velocity;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.item_touch_helper_swipe_escape_velocity = global::EsMo.Android.WeiBo.Resource.Dimension.item_touch_helper_swipe_escape_velocity;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.MvvmCrossTagId = global::EsMo.Android.WeiBo.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.MvxBindingTagUnique = global::EsMo.Android.WeiBo.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.item_touch_helper_previous_elevation = global::EsMo.Android.WeiBo.Resource.Id.item_touch_helper_previous_elevation;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxBinding = global::EsMo.Android.WeiBo.Resource.Styleable.MvxBinding;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxBinding_MvxBind = global::EsMo.Android.WeiBo.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxBinding_MvxLang = global::EsMo.Android.WeiBo.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxControl = global::EsMo.Android.WeiBo.Resource.Styleable.MvxControl;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxControl_MvxTemplate = global::EsMo.Android.WeiBo.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxExpandableListView = global::EsMo.Android.WeiBo.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::EsMo.Android.WeiBo.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxImageView = global::EsMo.Android.WeiBo.Resource.Styleable.MvxImageView;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxImageView_MvxSource = global::EsMo.Android.WeiBo.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxListView = global::EsMo.Android.WeiBo.Resource.Styleable.MvxListView;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::EsMo.Android.WeiBo.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxListView_MvxItemTemplate = global::EsMo.Android.WeiBo.Resource.Styleable.MvxListView_MvxItemTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxRecyclerView = global::EsMo.Android.WeiBo.Resource.Styleable.MvxRecyclerView;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxRecyclerView_MvxTemplateSelector = global::EsMo.Android.WeiBo.Resource.Styleable.MvxRecyclerView_MvxTemplateSelector;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView = global::EsMo.Android.WeiBo.Resource.Styleable.RecyclerView;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView_android_orientation = global::EsMo.Android.WeiBo.Resource.Styleable.RecyclerView_android_orientation;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView_layoutManager = global::EsMo.Android.WeiBo.Resource.Styleable.RecyclerView_layoutManager;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView_reverseLayout = global::EsMo.Android.WeiBo.Resource.Styleable.RecyclerView_reverseLayout;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView_spanCount = global::EsMo.Android.WeiBo.Resource.Styleable.RecyclerView_spanCount;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView_stackFromEnd = global::EsMo.Android.WeiBo.Resource.Styleable.RecyclerView_stackFromEnd;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int MvxBind = 2130771969;
			
			// aapt resource value: 0x7f010005
			public const int MvxDropDownItemTemplate = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int MvxGroupItemTemplate = 2130771974;
			
			// aapt resource value: 0x7f010004
			public const int MvxItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010002
			public const int MvxLang = 2130771970;
			
			// aapt resource value: 0x7f010007
			public const int MvxSource = 2130771975;
			
			// aapt resource value: 0x7f010003
			public const int MvxTemplate = 2130771971;
			
			// aapt resource value: 0x7f010000
			public const int MvxTemplateSelector = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int defaultSplash = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040000
			public const int MvvmCrossTagId = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int MvxBindingTagUnique = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int MyButton = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int linearLayout1 = 2130968579;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int SplashScreen = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771969,
					2130771970};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771971};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[] {
					2130771974};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771975};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771972,
					2130771973};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			public static int[] MvxRecyclerView = new int[] {
					2130771968};
			
			// aapt resource value: 0
			public const int MvxRecyclerView_MvxTemplateSelector = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
